### ISSUE TITLE
ImportError with current flask/werkzeug

### ISSUE THREAD

**Issue by fauxpark** [numberly/flask-graphite#18]
The following line now emits an `ImportError` when trying to use this library:

https://github.com/numberly/flask-graphite/blob/48f0fee5466a6c05cc4432d5277781bdbabd6dec/flask_graphite/utils.py#L2

Earlier this year `_rule_re` was moved to `rules.py` and then refactored away: https://github.com/pallets/werkzeug/commit/5a7c0dec029d296a5e8131c8db51ce19e28c0c58

**Comment by ramnes** [comment]
Oh, a fellow keyboard enthusiast. :)

@Shir0kamii and myself do not work at Numberly anymore, and I don't seem to have kept write access here.

Maybe it's still used and maintained internally though – any hint @Lujeni @shnups @rambobinator? If you guys do not want to maintain the library anymore, maybe you should consider archiving it or transfer it to anyone willing to maintain it.

**Comment by Lujeni** [comment]
@fauxpark @ramnes  yes and sorry :crying_cat_face: we do not maintain this lib anymore. 
I'll change the project settings. 

Feel free to fork :pray:
